import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '@/context/auth-context';
import { Button } from '@/components/ui/button';
import Link from 'next/link';
import Image from 'next/image';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="min-h-screen bg-white text-slate-900">
            {/* Header */}
            {/* <header className="px-6 py-6 flex justify-between items-center border-b border-slate-200">
              <h1 className="text-2xl font-bold">
                <Link href="/" className="text-blue-600 hover:text-blue-700">
                  <Image
                    src={ICyberScore.src}
                    width={66}
                    height={24}
                    alt="CyberScore Logo"
                    className="object-cover inline-block mr-2"
                  />
                </Link>
                </h1>
              <nav className="space-x-6 text-slate-600">
                <Link href="/#features" className="hover:text-slate-900">
                  Features
                </Link>
                <Link href="/#how-it-works" className="hover:text-slate-900">
                  How it Works
                </Link>
                <Link href="/#pricing" className="hover:text-slate-900">
                  Pricing
                </Link>
                <Link href="/#contact" className="hover:text-slate-900">
                  Contact
                </Link>
              </nav>
              <div>
                <Button
                  variant="outline"
                  className="mr-4 px-5 py-2 rounded-full border-slate-300 text-slate-700 hover:bg-slate-100 hover:border-slate-400 hover:text-slate-900 shadow-sm transition-all duration-200 ease-in-out"
                >
                  <Link href="/login" className="flex items-center">
                    Login
                  </Link>
                </Button>
                <Button className="px-5 py-2 rounded-full bg-blue-600 hover:bg-blue-700 text-white shadow-md hover:shadow-lg transition-all duration-200 ease-in-out">
                  Get Started
                </Button>
              </div>
            </header> */}

            {children}

            {/* Contact/Footer */}
            {/* <footer
              id="contact"
              className="border-t border-slate-200 py-10 text-center text-slate-500 text-sm"
            >
              <p>Contact us: support@cyberscore.ai</p>
              <p className="mt-2">
                © {new Date().getFullYear()} CyberScore. All rights reserved.
              </p>
            </footer> */}
          </div>
        </body>
      </AuthProvider>
    </html>
  );
}
